name: openapi_generator_cli
description: A dart wrapper around openapi-generator inspired by the node implementation.
version: 3.0.0-nullsafety.1
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

executables:
  openapi-generator: main
