name: openapi_generator_cli
description: A dart wrapper around openapi-generator inspired by the node implementation.
version: 2.0.0-beta
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4

executables:
  openapi-generator: main
